using System.IO;

namespace VideoEnhancer;

internal static class CliHelp
{
    internal static void Print(TextWriter writer, string toolVersion, string defaultModelScopeDataset)
    {
        writer.WriteLine("videoenhancer.exe — 视频/图片超分辨率命令行工具  v" + toolVersion);
        writer.WriteLine("============================================================");
        writer.WriteLine("用法");
        writer.WriteLine("  videoenhancer.exe -i <输入视频> -modelpath <模型目录> -ffmpeg-settings \"<FFmpeg 参数 + 输出路径>\"");
        writer.WriteLine("  videoenhancer.exe -i <输入视频> -interp-model <补帧模型> [-no-upscale] -ffmpeg-settings \"<FFmpeg 参数 + 输出路径>\"");
        writer.WriteLine("  videoenhancer.exe -i <输入视频> -no-upscale -backend cuda -interp-model <CUDA 补帧模型> -ffmpeg-settings \"<FFmpeg 参数 + 输出路径>\"");
        writer.WriteLine("  videoenhancer.exe --image-input <图片> --image-output <文件夹> -backend onnx -modelpath <模型>");
        writer.WriteLine("  videoenhancer.exe --image-folder <文件夹> --image-output-original -modelpath <模型>");
        writer.WriteLine("  videoenhancer.exe -i <输入视频> -backend rtxvsr -rtx-target 2160p -rtx-quality 3 -rtx-hdr -rtx-hdr-contrast 100 -ffmpeg-settings \"...\"");
        writer.WriteLine("  videoenhancer.exe --list-download-models --json");
        writer.WriteLine("  videoenhancer.exe --import-model <模型文件、目录或压缩包> --json");
        writer.WriteLine("  videoenhancer.exe --clean-download-archives");
        writer.WriteLine("  videoenhancer.exe --download-model <镜像相对路径>");
        writer.WriteLine("  videoenhancer.exe --delete-download-model <镜像相对路径>");
        writer.WriteLine("  videoenhancer.exe --backend-status --json");
        writer.WriteLine("  videoenhancer.exe --update-backend");
        writer.WriteLine("  videoenhancer.exe --apply-backend-patch <本地补丁包>");
        writer.WriteLine("  videoenhancer.exe --download-url <链接> --download-output <文件>");
        writer.WriteLine("  videoenhancer.exe --extract-archive <压缩包> [--extract-output <目录>]");
        writer.WriteLine("  videoenhancer.exe --third-party-notices");
        writer.WriteLine("  videoenhancer.exe --license");
        writer.WriteLine("  videoenhancer.exe --version");
        writer.WriteLine();
        writer.WriteLine("必需参数");
        writer.WriteLine("  -i, --input <路径>");
        writer.WriteLine("        输入视频路径，含空格时用双引号包裹，例如 -i \"D:\\videos\\input.mp4\"");
        writer.WriteLine("  -modelpath, --modelpath, --model <路径>");
        writer.WriteLine("        放大模型：可给完整路径、models 下的相对路径或模型名");
        writer.WriteLine("        （如 RealESRGAN-AnimeVideoV3-2x）；省略时使用默认模型；");
        writer.WriteLine("        配合 -no-upscale 时可不提供（仅补帧模式）");
        writer.WriteLine("  -ffmpeg-settings, --ffmpeg-settings <字符串>");
        writer.WriteLine("        FFmpeg 输出编码参数，最后一个参数必须是输出文件路径");
        writer.WriteLine("        （因此不需要 -o，输出路径内置于该参数中）");
        writer.WriteLine();
        writer.WriteLine("可选参数");
        writer.WriteLine("  -h, --help          显示本帮助并退出");
        writer.WriteLine("  -scale <N>          推理倍率，必须符合模型原生倍率；默认读取模型能力");
        writer.WriteLine("  -output-scale <N>   目标输出倍率（1–8）；超分结果先调整尺寸（TRT 图内缩小 / 其余 Lanczos），默认原生");
        writer.WriteLine("  -interp-model <路径>  补帧模型：完整路径、models\\Frame-Interpolation 下的相对路径或模型名");
        writer.WriteLine("        （如 RIFE/rife-v4.25、GIMM-VFI/gimm-vfi）；旧 models\\RIFE 目录仍可读取；");
        writer.WriteLine("        CUDA 使用 .pth/.pt/.pkl；TensorRT 使用 RIFE 权重自动构建 Engine；NCNN 使用 .param/.bin 文件夹");
        writer.WriteLine("  -interp-factor <N>  补帧倍率（帧率倍数，默认 2，需大于 1）");
        writer.WriteLine("  -process-order <upscale-first|interp-first>  组合处理顺序；默认 upscale-first");
        writer.WriteLine("        画质优先：先超分，再补帧。速度/算力优先：先补帧，再超分。");
        writer.WriteLine("  -upscale-precision <auto|float16|float32>  超分精度；默认 auto（FP16 优先，必要时回退）");
        writer.WriteLine("  -interp-precision <auto|float16|float32>  补帧精度；默认 auto（FP16 优先，必要时回退）");
        writer.WriteLine("        同后端组合也会分别应用两种精度，在内存中转换张量，不产生额外 FFV1 中间视频。");
        writer.WriteLine("  -interp-backend <ncnn|cuda|tensorrt>  可选的独立补帧后端；RIFE 实际支持 NCNN、CUDA/PyTorch、TensorRT");
        writer.WriteLine("  -scene-threshold <N>  转场检测阈值（RVE 官方外部 0-10 标尺；数值越低越敏感，默认 4）");
        writer.WriteLine("  -dynamic-optical-flow  开启 RIFE 动态光流尺度（仅 CUDA/PyTorch 补帧有效）");
        writer.WriteLine("  -tile-size <N>  超分分块边长（0 为 RVE 默认；至少 32；支持 NCNN/CUDA/TensorRT/ONNX）");
        writer.WriteLine("  -backend <ncnn|cuda|tensorrt|onnx|flashvsr|basicvsrpp|rtxvsr>  超分推理后端；");
        writer.WriteLine("        basicvsrpp 支持官方 x4 PTH，及 config.py/chkpts.pth 的 1x 优化目录；");
        writer.WriteLine("        所有后端均递归扫描 models 子目录；Frame-Interpolation 仅用于补帧；");
        writer.WriteLine("        cuda 使用 .pth/.pt/.pkl/.ckpt/.safetensors；tensorrt 接受可转换权重，缺少缓存时会自动构建；");
        writer.WriteLine("        TensorRT 缓存名包含 GPU、TensorRT 版本、输入尺寸和源模型摘要；onnx 使用 .onnx；");
        writer.WriteLine("        超分与补帧可同时指定；同一后端逐帧执行，跨后端才使用 FFV1 无损中间视频；");
        writer.WriteLine("        SDR 内部为 8-bit RGB；PQ/HLG 使用 16-bit RGB，且仅支持 CUDA/PyTorch 或 TensorRT");
        writer.WriteLine("  -rtx-target <规格>  RTX VSR 输出规格：1x/1.5x/2x/3x/4x 或 1080p/1440p/2160p/4320p；最大 4x，输出边长取偶数");
        writer.WriteLine("  -rtx-quality <1-4>  RTX VSR 质量等级，默认 3");
        writer.WriteLine("  -rtx-hdr            启用 RTX Video HDR；输入已是 PQ/HLG 时会拒绝重复映射");
        writer.WriteLine("  -rtx-hdr-contrast <0-200>       RTX HDR 对比度，默认 100，可输入范围内任意整数");
        writer.WriteLine("  -rtx-hdr-saturation <0-200>     RTX HDR 饱和度，默认 100，可输入范围内任意整数");
        writer.WriteLine("  -rtx-hdr-middle-gray <10-100>   RTX HDR 中灰度，默认 44，可输入范围内任意整数");
        writer.WriteLine("  -rtx-hdr-max-luminance <400-2000> RTX HDR 最大亮度（nit），默认 1000，可输入范围内任意整数");
        writer.WriteLine("  --segments-base64 <Base64 JSON>");
        writer.WriteLine("        分段配置；默认禁止 NCNN/CUDA/TensorRT/ONNX 跨模型后端混用，FFmpeg/Anime4K 不受此限制");
        writer.WriteLine("  --allow-mixed-segment-backends  实验功能：显式允许分段跨 NCNN/CUDA/TensorRT/ONNX 混用");
        writer.WriteLine("  -no-upscale         不放大（可用于仅补帧或仅 RTX HDR）");
        writer.WriteLine("  -pause-shm <ID>     暂停共享内存名（透传给 rve-backend --pause_shared_memory_id）");
        writer.WriteLine("  -stop-shm <ID>      停止共享内存名：字节变 1 时优雅停止，已处理部分写入输出文件");
        writer.WriteLine("  --list-models, --search-models  列出可用的放大模型并退出（默认 ncnn 文件夹）");
        writer.WriteLine("        各后端均递归列出 models 子目录中的对应放大模型（排除补帧目录）；");
        writer.WriteLine("        （配合 --json 输出一行 JSON 数组，供界面程序解析）");
        writer.WriteLine("  --list-model-catalog / --list-interp-model-catalog  输出带架构、倍率、来源和后端能力的结构化模型清单");
        writer.WriteLine("  --list-user-models --json  输出用户导入模型的完整能力清单");
        writer.WriteLine("  --inspect-upscale-model <权重>  安全预检 PTH/PT/CKPT/safetensors/ONNX 的架构、倍率和尺寸能力");
        writer.WriteLine("  --import-model <路径>  预检文件、目录或压缩包，通过后原子安装到 models\\User 并登记能力清单");
        writer.WriteLine("  --update-user-model <ID>  配合 --user-* 参数校验并修正用户模型能力");
        writer.WriteLine("  --delete-user-model <ID>  删除用户模型文件、目录及其能力清单记录");
        writer.WriteLine("  --list-interp-models  列出 models\\Frame-Interpolation 下可用的补帧模型并退出");
        writer.WriteLine("        （配合 --json 输出一行 JSON 数组，供界面程序解析）；");
        writer.WriteLine("        加 -interp-backend cuda 列出全部 PyTorch 权重，tensorrt 只列 RIFE 权重；旧 RIFE 兼容读取");
        writer.WriteLine("  --check             仅检测运行环境（ffmpeg / python 库 / 模型库）并退出");
        writer.WriteLine("  --list-backends     列出后端，并逐个在当前 GPU 上反序列化 models 中的 TensorRT Engine");
        writer.WriteLine("  --validate-engines  递归验证全部 .engine；不兼容时提示在当前 GPU 上重新编译");
        writer.WriteLine("  --inspect-interp-model <权重>  按权重内容识别补帧架构，并输出 CUDA/TensorRT 能力 JSON");
        writer.WriteLine("  --prepare-interp-engine <RIFE 权重> --prepare-width <宽> --prepare-height <高>");
        writer.WriteLine("        用 RVE 的 RIFE flow/encode 路径预构建 TensorRT Engine；支持 .pth/.pt/.pkl");
        writer.WriteLine("        可加 --prepare-static-shape 强制按指定分辨率构建静态 Engine");
        writer.WriteLine("  --list-download-models  从 ModelScope 镜像读取可下载文件；配合 --json 输出给界面");
        writer.WriteLine("        默认仓库：" + defaultModelScopeDataset);
        writer.WriteLine("        VIDEOENHANCER_MODELSCOPE_DATASET 可覆盖仓库 ID；私有仓库需设置");
        writer.WriteLine("        VIDEOENHANCER_MODELSCOPE_TOKEN 或 MODELSCOPE_API_TOKEN（不会写入配置文件）");
        writer.WriteLine("  --clean-download-archives  清理 models、python 与 RTX runtime 专用目录中的下载压缩包");
        writer.WriteLine("  --download-model <路径>  用独立安装的 aria2-next 下载镜像文件；压缩包自动用独立 7za 解压");
        writer.WriteLine("  --delete-download-model <路径>  删除本地单文件模型；RTX runtime 路径执行专用卸载，其他组件与压缩包拒绝删除");
        writer.WriteLine("  --backend-status [--json]  检查后端版本、可用增量补丁和预计下载大小");
        writer.WriteLine("  --update-backend  按最小补丁链事务更新后端；失败或中断时自动回滚");
        writer.WriteLine("  --force-backend-full  配合 --update-backend，跳过增量补丁并下载完整修复包");
        writer.WriteLine("  --apply-backend-patch <文件>  离线应用后端增量补丁");
        writer.WriteLine("  --backend-channel <URL或文件>  指定更新通道；也可设置 VIDEOENHANCER_BACKEND_CHANNEL");
        writer.WriteLine("  --download-url <链接> --download-output <文件>  使用独立安装的 aria2-next 下载任意直链");
        writer.WriteLine("  --extract-archive <文件> [--extract-output <目录>]  使用独立 7za 解压（7z/ZIP/TAR/GZip/XZ/BZip2/Zstd）");
        writer.WriteLine("  --third-party-notices  显示第三方组件和许可证信息");
        writer.WriteLine("  --license  显示 VideoEnhancer 项目 MIT 许可证");
        writer.WriteLine("  --image-input <文件>  添加一个图片输入（可重复）");
        writer.WriteLine("  --image-folder <目录>  递归添加目录及其子目录图片（可重复）");
        writer.WriteLine("  --image-output <目录>  指定图片输出目录；或用 --image-output-original 输出到原目录");
        writer.WriteLine("  --image-suffix <timestamp|model>  文件名附加处理时间戳或模型名称");
        writer.WriteLine("  --image-png / --image-source-format  输出无损 PNG（默认）或保持源扩展格式");
        writer.WriteLine();
        writer.WriteLine("说明");
        writer.WriteLine("  · 便携目录：CoreRoot 永远是 videoenhancer.exe 所在目录；");
        writer.WriteLine("    不读取或写入 videoenhancer.ini，cache、.work 和 .update 始终位于 EXE 目录内。");
        writer.WriteLine("  · FFmpeg 优先使用 3FUI EXE 同目录或 PATH 中的 ffmpeg.exe/ffprobe.exe；");
        writer.WriteLine("    插件旧版 bin\\ffmpeg 仅作兼容回退。其余检测 CoreRoot 下的 python 与 models；");
        writer.WriteLine("    任一缺失会报错并标出缺失项。");
        writer.WriteLine("  · ffmpeg-settings 是“编码参数 + 输出文件”的完整片段，程序会中转给");
        writer.WriteLine("    rve-backend（--custom_encoder 与 -o）。输出路径必须是最后一个参数；");
        writer.WriteLine("    末尾可加 -y 表示覆盖已存在文件。");
        writer.WriteLine("    -map 流映射会被自动移除（后端写进程自带映射），-map_metadata / -map_chapters");
        writer.WriteLine("    的源输入索引自动从 0 改写为 1（后端写进程中源文件为输入 1）。");
        writer.WriteLine("  · 带空格的参数值请用双引号包裹；编码参数需要完整（如像素格式），");
        writer.WriteLine("    与 GUI“参数总览”生成的片段一致。");
        writer.WriteLine();
        writer.WriteLine("示例（PowerShell）");
        writer.WriteLine("  .\\videoenhancer.exe -i \"D:\\videos\\input.mp4\" -modelpath RealESRGAN-AnimeVideoV3-2x `");
        writer.WriteLine("      -ffmpeg-settings '-c:v av1_nvenc -preset:v p4 -cq:v 38 -pix_fmt:v p010le `");
        writer.WriteLine("                       -c:a libopus -b:a 192k \"D:\\videos\\input_upscaled.mkv\"'");
        writer.WriteLine();
        writer.WriteLine("示例（cmd）");
        writer.WriteLine("  videoenhancer.exe -i \"D:\\videos\\input.mp4\" -modelpath RealESRGAN-AnimeVideoV3-2x `");
        writer.WriteLine("      -ffmpeg-settings \"-c:v libx264 -crf 18 -c:a aac \\\"D:\\videos\\out.mp4\\\"\"");
        writer.WriteLine("示例（cmd，仅补帧 2x）");
        writer.WriteLine("  videoenhancer.exe -i \"D:\\videos\\input.mp4\" -no-upscale -interp-model rife-v4.25 `");
        writer.WriteLine("      -ffmpeg-settings \"-c:v libx264 -crf 18 -r 60 \\\"D:\\videos\\out_60fps.mp4\\\"\"");
        writer.WriteLine();
        writer.WriteLine("退出码");
        writer.WriteLine("  0 成功；1 处理失败或环境错误；2 参数错误；130 用户中止");
        writer.WriteLine();
        writer.WriteLine("说明：本工具是 Video Enhancer GUI 的 rve-backend 命令行中转器，后端逻辑");
        writer.WriteLine("与 GUI 完全一致（ncnn 后端、场景检测、倍率自动识别等）。");
        writer.WriteLine("  · 放大模型递归扫描 models：NCNN 取 .param/.bin 文件夹，CUDA 取 .pth/.pt/.pkl/.ckpt/.safetensors，");
        writer.WriteLine("    TensorRT 取可转换源权重，并把自动构建结果写入 models\\TensorRT-Cache；");
        writer.WriteLine("    models\\Frame-Interpolation 独立保留给补帧模型，旧 models\\RIFE 兼容读取；");
        writer.WriteLine("    （rve-backend 的 spandrel/InterpolateRIFE 加载）。");
    }}
